### ISSUE TITLE
Supports <= 3.4 but using typing module new in version 3.5

### ISSUE THREAD

**Issue by manjuu-eater** [ikegami-yukino/jaconv#24]
Python3.4以下もサポートされているようですが、typingモジュールはPython3.5で追加されたようです。
https://docs.python.org/ja/3/library/typing.html

Python3.4の環境で検証ができなかったのですが、とりあえず型ヒントのある記法はPython2.7ではinvalid syntaxになるようです…（[Wandboxで確認](https://wandbox.org/permlink/dmfAm9uDyK6OAz7S)）

`enlargesmallkana()`にある型ヒントは<=3.4の環境で邪魔にならないのでしょうか？

いまいち確証が持てていなくて申し訳ないです。よろしくお願いします。

**Comment by manjuu-eater** [comment]
Python2.7.18を入れてインストールしてみたのですが、やっぱりSyntaxErrorになってしまっていました…。
typingを除去してプルリクエストを出してみます。

よろしくお願いします。

```
D:\>py -2
Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import jaconv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\AppData\Roaming\Python\Python27\site-packages\jaconv\__init__.py", line 3, in <module>
    from . import jaconv
  File "C:\Users\User\AppData\Roaming\Python\Python27\site-packages\jaconv\jaconv.py", line 27
    def _translate(text: str, ignore: str, conv_map: typing.Dict) -> str:
                       ^
SyntaxError: invalid syntax
>>>
```
